all: 
	 g++ -std=c++14 main.cpp polynomial.h polynomial.cpp
	 
#polynomial.cpp
#CFLAGS = -std=c++14
#OBJECTS = main.o 

#all: hello

#hello: main.o polynomial.o

#main.o: main.cpp 
#	$(CC) main.cpp

#polynomial.o: polynomial.cpp 
#	$(CC) polynomial.cpp